org: slisandro
app: aeg
service: aeg-admin

provider: 
  name: aws
  runtime: nodejs16.x
  region: us-east-2
  environment:
    DYNAMODB_ACCESS_KEY: process.env.DYNAMODB_ACCESS_KEY 
    DYNAMODB_SECRET_ACCESS_KEY: process.env.DYNAMODB_SECRET_ACCESS_KEY
  httpApi:
    cors: true
functions:
  graphql:
    handler: dist/index.handler
    events:
      - httpApi: 
          path: /
          method: POST
      - httpApi: 
          path: /
          method: GET
plugins: 
  - serverless-offline
custom:
  serverless-offline: 
    noTimeout: true